apiVersion: v1
kind: Service
metadata:
  name: echo1
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: echo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 2
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
      - name: echo1
        image: hashicorp/http-echo
        args:
        - "-text=echo1"
        ports:
        - containerPort: 5678
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    #certmanager.k8s.io/cluster-issuer: letsencrypt-production
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
  name: test-ingress120
#  namespace: myIngress
spec:
  rules:
  - host: test11.k8s.angrynet.ninja
    http:
      paths:
      - backend:
          serviceName: echo1
          servicePort: 80
        path: /
  tls:
  - hosts:
    - test10.k8s.angrynet.ninja
    secretName: test-ingress120
