apiVersion: v1
kind: Service
metadata:
  name: echo1
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: echo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 2
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
      - name: echo1
        image: hashicorp/http-echo
        args:
        - "-text=echo1"
        ports:
        - containerPort: 5678
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     # add an annotation indicating the issuer to use.
#     #certmanager.k8s.io/cluster-issuer: letsencrypt-production
#     cert-manager.io/cluster-issuer: letsencrypt-staging
#     kubernetes.io/ingress.class: nginx-internal
#   name: test-ingress
# #  namespace: myIngress
# spec:
#   rules:
#   - host: test.angryninja.cloud
#     http:
#       paths:
#       - backend:
#           serviceName: echo1
#           servicePort: 80
#         path: /
#   tls:
#   - hosts:
#     - test.angryninja.cloud
#     secretName: test-ingress
---
# apiVersion: networking.k8s.io/v1beta1
# kind: IngressClass
# metadata:
#   name: internal-ingress
#   annotations:
#     ingressclass.kubernetes.io/is-default-class: "true"
# spec:
#   controller: getambassador.io/ingress-controller

apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: internal-lb
spec:
  controller: angryninja.cloud/ingress-controller
  parameters:
    apiGroup: k8s.angryninja.cloud/v1alpha
    kind: IngressParameters
    name: internal-lb


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-example-ingress
  cert-manager.io/cluster-issuer: letsencrypt-staging
  kubernetes.io/ingress.class: nginx-internal
spec:
  tls:
  - hosts:
      - test.angryninja.cloud
    secretName: testsecret-tls
  rules:
  - host: test.angryninja.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo1
            port:
              number: 80