#https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager
ingressShim:
  defaultIssuerName: letsencrypt-staging
  defaultIssuerKind: ClusterIssuer

# Needed to change DNS lookups to public service
podDnsPolicy: "None"
podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"
