apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gitlab-ce.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "gitlab-ce.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "gitlab-ce.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "gitlab-ce.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlab.RootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.gitlab.ExternalUrl | quote }}
        ## DB configuration
        ##
        - name: DB_HOST
          value: {{ template "gitlab-ce.postgresql.fullname" . }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: db-password
        - name: DB_DATABASE
          value: {{ .Values.postgresql.postgresqlDatabase | quote }}

        ## Redis configuration
        ##
        - name: REDIS_HOST
          value: {{ template "gitlab-ce.redis.fullname" . }}-master

        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: redis-password

        ## SMTP configuration
        ##
        
        - name: SMTP_ADDRESS
          value: {{ .Values.gitlab.smtp.address | quote }}

        - name: SMTP_USER
          value: {{ .Values.gitlab.smtp.user | quote }}
                    
        - name: SMTP_DOMAIN
          value: {{ .Values.gitlab.smtp.domain | quote }}

        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: smtp-password

        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /help
            port: 80
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 500
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 16
        readinessProbe:
          httpGet:
            path: /help
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3

        volumeMounts:
        - name: gitlab-data
          mountPath: /etc/gitlab
          subPath: config
        - name: gitlab-data
          mountPath: /gitlab-data
          subPath: data
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: gitlab-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "gitlab-ce.fullname" . }}-data{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
