{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gitlab-ce.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
    - host: {{ .Values.ingress.url | quote }}
      http:
        paths:
        - backend:
            serviceName: {{ template "gitlab-ce.fullname" . }}
            servicePort: {{ .Values.service.http.port | int }}

{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
