apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gitlab-ce.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if default "" .Values.gitlabRootPassword }}
  # Defaulting to a non-sensical value to silence b64enc warning. We'll never
  # actually use this default due to the if statement.
  gitlab-root-password: {{ default "ignore" .Values.gitlabRootPassword | b64enc | quote }}
  {{ end }}
  db-user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  db-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  smtp-password: {{ .Values.gitlab.smtp.password | b64enc | quote }}
