
image:
  repository: pihole/pihole
  tag: v5.3.4
  pullPolicy: IfNotPresent

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

config:
  webpassword: admin
  timezone: Australia/Sydney

## Ingress configuration options
##
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: /
  tls:
    #- secretName: pihole-local-tls
    #  hosts:
    #    - pihole.local
  url: pihole.local

## External service ports
service:
  http:
    type: ClusterIP
    enabled: true
    port: 80
    #nodePort: 30280
  dns:
    type: ClusterIP
    enabled: true
    port: 53
    #nodePort: 30222

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

persistence:
  enabled: false
  size: 5Gi


  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  ## Manually managed PVC
  # existingClaim:

  accessMode: ReadWriteOnce

# Probes configuration
probes:
  liveness:
    initialDelaySeconds: 180
    failureThreshold: 5
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 5
    failureThreshold: 5
    timeoutSeconds: 5

nodeSelector: {}

affinity: {}

tolerations: {}
