apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
 # storageClassName: nfs
  nfs:
    path: /volume1/media
    server: nas.angrynet.ninja
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
 # storageClassName: nfs
  resources:
    requests:
      storage: 10Ti
