apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pihole.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "pihole.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  web-password: {{ .Values.config.webpassword | b64enc | quote }}
