{{- $fullName := include "bitwarden.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitwarden.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "bitwarden.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
